// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: AllocationAuthorityInfo.capnp

#pragma once

#include <capnp/generated-header-support.h>
#include <kj/windows-sanity.h>

#if CAPNP_VERSION != 7000
#error "Version mismatch between generated code and library headers.  You must use the same version of the Cap'n Proto compiler and library."
#endif

#include <capnzero/ID.capnp.h>

namespace capnp {
namespace schemas {

CAPNP_DECLARE_SCHEMA(9d606d9272d3600d);
CAPNP_DECLARE_SCHEMA(9fdac7c5cfd18be3);

}  // namespace schemas
}  // namespace capnp

namespace alica_msgs {

struct AllocationAuthorityInfo {
  AllocationAuthorityInfo() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(9d606d9272d3600d, 3, 3)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct EntrypointRobots {
  EntrypointRobots() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(9fdac7c5cfd18be3, 1, 1)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

// =======================================================================================

class AllocationAuthorityInfo::Reader {
public:
  typedef AllocationAuthorityInfo Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline bool hasSenderId() const;
  inline  ::capnzero::ID::Reader getSenderId() const;

  inline  ::int64_t getPlanId() const;

  inline  ::int64_t getParentState() const;

  inline  ::int64_t getPlanType() const;

  inline bool hasAuthority() const;
  inline  ::capnzero::ID::Reader getAuthority() const;

  inline bool hasEntrypointRobots() const;
  inline  ::capnp::List< ::alica_msgs::EntrypointRobots,  ::capnp::Kind::STRUCT>::Reader getEntrypointRobots() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class AllocationAuthorityInfo::Builder {
public:
  typedef AllocationAuthorityInfo Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline bool hasSenderId();
  inline  ::capnzero::ID::Builder getSenderId();
  inline void setSenderId( ::capnzero::ID::Reader value);
  inline  ::capnzero::ID::Builder initSenderId();
  inline void adoptSenderId(::capnp::Orphan< ::capnzero::ID>&& value);
  inline ::capnp::Orphan< ::capnzero::ID> disownSenderId();

  inline  ::int64_t getPlanId();
  inline void setPlanId( ::int64_t value);

  inline  ::int64_t getParentState();
  inline void setParentState( ::int64_t value);

  inline  ::int64_t getPlanType();
  inline void setPlanType( ::int64_t value);

  inline bool hasAuthority();
  inline  ::capnzero::ID::Builder getAuthority();
  inline void setAuthority( ::capnzero::ID::Reader value);
  inline  ::capnzero::ID::Builder initAuthority();
  inline void adoptAuthority(::capnp::Orphan< ::capnzero::ID>&& value);
  inline ::capnp::Orphan< ::capnzero::ID> disownAuthority();

  inline bool hasEntrypointRobots();
  inline  ::capnp::List< ::alica_msgs::EntrypointRobots,  ::capnp::Kind::STRUCT>::Builder getEntrypointRobots();
  inline void setEntrypointRobots( ::capnp::List< ::alica_msgs::EntrypointRobots,  ::capnp::Kind::STRUCT>::Reader value);
  inline  ::capnp::List< ::alica_msgs::EntrypointRobots,  ::capnp::Kind::STRUCT>::Builder initEntrypointRobots(unsigned int size);
  inline void adoptEntrypointRobots(::capnp::Orphan< ::capnp::List< ::alica_msgs::EntrypointRobots,  ::capnp::Kind::STRUCT>>&& value);
  inline ::capnp::Orphan< ::capnp::List< ::alica_msgs::EntrypointRobots,  ::capnp::Kind::STRUCT>> disownEntrypointRobots();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class AllocationAuthorityInfo::Pipeline {
public:
  typedef AllocationAuthorityInfo Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

  inline  ::capnzero::ID::Pipeline getSenderId();
  inline  ::capnzero::ID::Pipeline getAuthority();
private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class EntrypointRobots::Reader {
public:
  typedef EntrypointRobots Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline  ::int64_t getEntrypoint() const;

  inline bool hasRobots() const;
  inline  ::capnp::List< ::capnzero::ID,  ::capnp::Kind::STRUCT>::Reader getRobots() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class EntrypointRobots::Builder {
public:
  typedef EntrypointRobots Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline  ::int64_t getEntrypoint();
  inline void setEntrypoint( ::int64_t value);

  inline bool hasRobots();
  inline  ::capnp::List< ::capnzero::ID,  ::capnp::Kind::STRUCT>::Builder getRobots();
  inline void setRobots( ::capnp::List< ::capnzero::ID,  ::capnp::Kind::STRUCT>::Reader value);
  inline  ::capnp::List< ::capnzero::ID,  ::capnp::Kind::STRUCT>::Builder initRobots(unsigned int size);
  inline void adoptRobots(::capnp::Orphan< ::capnp::List< ::capnzero::ID,  ::capnp::Kind::STRUCT>>&& value);
  inline ::capnp::Orphan< ::capnp::List< ::capnzero::ID,  ::capnp::Kind::STRUCT>> disownRobots();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class EntrypointRobots::Pipeline {
public:
  typedef EntrypointRobots Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

// =======================================================================================

inline bool AllocationAuthorityInfo::Reader::hasSenderId() const {
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool AllocationAuthorityInfo::Builder::hasSenderId() {
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::capnzero::ID::Reader AllocationAuthorityInfo::Reader::getSenderId() const {
  return ::capnp::_::PointerHelpers< ::capnzero::ID>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::capnzero::ID::Builder AllocationAuthorityInfo::Builder::getSenderId() {
  return ::capnp::_::PointerHelpers< ::capnzero::ID>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
#if !CAPNP_LITE
inline  ::capnzero::ID::Pipeline AllocationAuthorityInfo::Pipeline::getSenderId() {
  return  ::capnzero::ID::Pipeline(_typeless.getPointerField(0));
}
#endif  // !CAPNP_LITE
inline void AllocationAuthorityInfo::Builder::setSenderId( ::capnzero::ID::Reader value) {
  ::capnp::_::PointerHelpers< ::capnzero::ID>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::capnzero::ID::Builder AllocationAuthorityInfo::Builder::initSenderId() {
  return ::capnp::_::PointerHelpers< ::capnzero::ID>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void AllocationAuthorityInfo::Builder::adoptSenderId(
    ::capnp::Orphan< ::capnzero::ID>&& value) {
  ::capnp::_::PointerHelpers< ::capnzero::ID>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnzero::ID> AllocationAuthorityInfo::Builder::disownSenderId() {
  return ::capnp::_::PointerHelpers< ::capnzero::ID>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline  ::int64_t AllocationAuthorityInfo::Reader::getPlanId() const {
  return _reader.getDataField< ::int64_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}

inline  ::int64_t AllocationAuthorityInfo::Builder::getPlanId() {
  return _builder.getDataField< ::int64_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}
inline void AllocationAuthorityInfo::Builder::setPlanId( ::int64_t value) {
  _builder.setDataField< ::int64_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, value);
}

inline  ::int64_t AllocationAuthorityInfo::Reader::getParentState() const {
  return _reader.getDataField< ::int64_t>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS);
}

inline  ::int64_t AllocationAuthorityInfo::Builder::getParentState() {
  return _builder.getDataField< ::int64_t>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS);
}
inline void AllocationAuthorityInfo::Builder::setParentState( ::int64_t value) {
  _builder.setDataField< ::int64_t>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS, value);
}

inline  ::int64_t AllocationAuthorityInfo::Reader::getPlanType() const {
  return _reader.getDataField< ::int64_t>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS);
}

inline  ::int64_t AllocationAuthorityInfo::Builder::getPlanType() {
  return _builder.getDataField< ::int64_t>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS);
}
inline void AllocationAuthorityInfo::Builder::setPlanType( ::int64_t value) {
  _builder.setDataField< ::int64_t>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS, value);
}

inline bool AllocationAuthorityInfo::Reader::hasAuthority() const {
  return !_reader.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
}
inline bool AllocationAuthorityInfo::Builder::hasAuthority() {
  return !_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
}
inline  ::capnzero::ID::Reader AllocationAuthorityInfo::Reader::getAuthority() const {
  return ::capnp::_::PointerHelpers< ::capnzero::ID>::get(_reader.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
inline  ::capnzero::ID::Builder AllocationAuthorityInfo::Builder::getAuthority() {
  return ::capnp::_::PointerHelpers< ::capnzero::ID>::get(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
#if !CAPNP_LITE
inline  ::capnzero::ID::Pipeline AllocationAuthorityInfo::Pipeline::getAuthority() {
  return  ::capnzero::ID::Pipeline(_typeless.getPointerField(1));
}
#endif  // !CAPNP_LITE
inline void AllocationAuthorityInfo::Builder::setAuthority( ::capnzero::ID::Reader value) {
  ::capnp::_::PointerHelpers< ::capnzero::ID>::set(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), value);
}
inline  ::capnzero::ID::Builder AllocationAuthorityInfo::Builder::initAuthority() {
  return ::capnp::_::PointerHelpers< ::capnzero::ID>::init(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
inline void AllocationAuthorityInfo::Builder::adoptAuthority(
    ::capnp::Orphan< ::capnzero::ID>&& value) {
  ::capnp::_::PointerHelpers< ::capnzero::ID>::adopt(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnzero::ID> AllocationAuthorityInfo::Builder::disownAuthority() {
  return ::capnp::_::PointerHelpers< ::capnzero::ID>::disown(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}

inline bool AllocationAuthorityInfo::Reader::hasEntrypointRobots() const {
  return !_reader.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS).isNull();
}
inline bool AllocationAuthorityInfo::Builder::hasEntrypointRobots() {
  return !_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::List< ::alica_msgs::EntrypointRobots,  ::capnp::Kind::STRUCT>::Reader AllocationAuthorityInfo::Reader::getEntrypointRobots() const {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::alica_msgs::EntrypointRobots,  ::capnp::Kind::STRUCT>>::get(_reader.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS));
}
inline  ::capnp::List< ::alica_msgs::EntrypointRobots,  ::capnp::Kind::STRUCT>::Builder AllocationAuthorityInfo::Builder::getEntrypointRobots() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::alica_msgs::EntrypointRobots,  ::capnp::Kind::STRUCT>>::get(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS));
}
inline void AllocationAuthorityInfo::Builder::setEntrypointRobots( ::capnp::List< ::alica_msgs::EntrypointRobots,  ::capnp::Kind::STRUCT>::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::alica_msgs::EntrypointRobots,  ::capnp::Kind::STRUCT>>::set(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS), value);
}
inline  ::capnp::List< ::alica_msgs::EntrypointRobots,  ::capnp::Kind::STRUCT>::Builder AllocationAuthorityInfo::Builder::initEntrypointRobots(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::alica_msgs::EntrypointRobots,  ::capnp::Kind::STRUCT>>::init(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS), size);
}
inline void AllocationAuthorityInfo::Builder::adoptEntrypointRobots(
    ::capnp::Orphan< ::capnp::List< ::alica_msgs::EntrypointRobots,  ::capnp::Kind::STRUCT>>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::alica_msgs::EntrypointRobots,  ::capnp::Kind::STRUCT>>::adopt(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::List< ::alica_msgs::EntrypointRobots,  ::capnp::Kind::STRUCT>> AllocationAuthorityInfo::Builder::disownEntrypointRobots() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::alica_msgs::EntrypointRobots,  ::capnp::Kind::STRUCT>>::disown(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS));
}

inline  ::int64_t EntrypointRobots::Reader::getEntrypoint() const {
  return _reader.getDataField< ::int64_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}

inline  ::int64_t EntrypointRobots::Builder::getEntrypoint() {
  return _builder.getDataField< ::int64_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}
inline void EntrypointRobots::Builder::setEntrypoint( ::int64_t value) {
  _builder.setDataField< ::int64_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, value);
}

inline bool EntrypointRobots::Reader::hasRobots() const {
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool EntrypointRobots::Builder::hasRobots() {
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::List< ::capnzero::ID,  ::capnp::Kind::STRUCT>::Reader EntrypointRobots::Reader::getRobots() const {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::capnzero::ID,  ::capnp::Kind::STRUCT>>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::capnp::List< ::capnzero::ID,  ::capnp::Kind::STRUCT>::Builder EntrypointRobots::Builder::getRobots() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::capnzero::ID,  ::capnp::Kind::STRUCT>>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void EntrypointRobots::Builder::setRobots( ::capnp::List< ::capnzero::ID,  ::capnp::Kind::STRUCT>::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::capnzero::ID,  ::capnp::Kind::STRUCT>>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::capnp::List< ::capnzero::ID,  ::capnp::Kind::STRUCT>::Builder EntrypointRobots::Builder::initRobots(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::capnzero::ID,  ::capnp::Kind::STRUCT>>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), size);
}
inline void EntrypointRobots::Builder::adoptRobots(
    ::capnp::Orphan< ::capnp::List< ::capnzero::ID,  ::capnp::Kind::STRUCT>>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::capnzero::ID,  ::capnp::Kind::STRUCT>>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::List< ::capnzero::ID,  ::capnp::Kind::STRUCT>> EntrypointRobots::Builder::disownRobots() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::capnzero::ID,  ::capnp::Kind::STRUCT>>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

}  // namespace

